apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Full Lifecycle
    categories: Security
    certified: 'False'
    containerImage: registry.redhat.io/rh-sso-7/sso7-rhel8-operator@sha256:369cc19c3c6340978208389499775f687ea752e792c5bd8f5a689571f14b84da
    createdAt: 2021-08-09 00:00:00
    description: 'An Operator for installing and managing Red Hat Single Sign-On'
    repository: 'https://github.com/keycloak/keycloak-operator'
    support: Red Hat
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
    alm-examples: |-
      [
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "Keycloak",
          "metadata": {
            "name": "example-keycloak",
            "labels": {
              "app": "sso"
            }
          },
          "spec": {
            "instances": 1,
            "externalAccess": {
              "enabled": true
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakRealm",
          "metadata": {
            "name": "example-keycloakrealm"
          },
          "spec": {
            "realm": {
              "id": "basic",
              "realm": "basic",
              "enabled": true,
              "displayName": "Basic Realm"
            },
            "instanceSelector": {
              "matchLabels": {
                "app": "sso"
              }
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakBackup",
          "metadata": {
            "name": "example-keycloakbackup"
          },
          "spec": {
            "instanceSelector": {
              "matchLabels": {
                "app": "sso"
              }
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakClient",
          "metadata": {
            "name": "client-secret",
            "labels": {
              "app": "sso"
            }
          },
          "spec": {
            "realmSelector": {
              "matchLabels": {
                "app": "sso"
              }
            },
            "client": {
              "clientId": "client-secret",
              "secret": "client-secret",
              "clientAuthenticatorType": "client-secret"
            }
          }
        },
        {
          "apiVersion": "keycloak.org/v1alpha1",
          "kind": "KeycloakUser",
          "metadata": {
            "name": "example-realm-user",
            "labels": {
              "app": "sso"
            }
          },
          "spec": {
            "user": {
              "username": "realm_user",
              "firstName": "John",
              "lastName": "Doe",
              "email": "user@example.com",
              "enabled": true,
              "emailVerified": false
            },
            "realmSelector": {
              "matchLabels": {
                "app": "sso"
              }
            }
          }
        }
      ]
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/tls-profiles: "false"
  name: rhsso-operator.7.6.11-opr-001
  namespace: placeholder
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/os.linux: supported
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: "Represents a Red Hat Single Sign-On Instance"
      displayName: "Keycloak"
      kind: Keycloak
      name: keycloaks.keycloak.org
      version: v1alpha1
    - description: "Represents a Red Hat Single Sign-On Realm"
      displayName: "KeycloakRealm"
      kind: KeycloakRealm
      name: keycloakrealms.keycloak.org
      version: v1alpha1
    - description: "Represents a Red Hat Single Sign-On Backup"
      displayName: "KeycloakBackup"
      kind: KeycloakBackup
      name: keycloakbackups.keycloak.org
      version: v1alpha1
    - description: "Represents a Red Hat Single Sign-On Client"
      displayName: "KeycloakClient"
      kind: KeycloakClient
      name: keycloakclients.keycloak.org
      version: v1alpha1
    - description: "Represents a Red Hat Single Sign-On User"
      displayName: "KeycloakUser"
      kind: KeycloakUser
      name: keycloakusers.keycloak.org
      version: v1alpha1
  description: |
    A Kubernetes Operator based on the Operator SDK for installing and managing Red Hat Single Sign-On.

    Red Hat Single Sign-On lets you add authentication to applications and secure services with minimum fuss. No need to deal with storing users or authenticating users. It's all available out of the box.

    The operator can deploy and manage Keycloak instances on Kubernetes and OpenShift.
    The following features are supported:

    * Install Keycloak to a namespace
    * Import Keycloak Realms
    * Import Keycloak Clients
    * Import Keycloak Users
    * Create scheduled backups of the database
  displayName: Red Hat Single Sign-On Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAVQAAAC1CAYAAAAA/QcmAAARRElEQVR4nO3dTWgjaWLG8cfuj2n3eKbkpqGHkNmqueSwJJH6kLlkEtVcwkII1pLLHhYkJ7AJ5OC6DCQnqZlDAlmwOqfksLgMCSTsBMuBXSZLQGXYHLJM4nKyl82lS9tZyGZMS/J0tz1utyuHXgvbbX2/Ukny/weCGUuqel1tPXq/ay6O41gAgKHNJ10AAJgVBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgAoAhBCoAGEKgYqxehqFOoqiv13/huqrPzak+N6cvXFfPPU/HQTCyMgKDmovjOE66EJhtcaOhg1JJR76vuNmUJM1Zlm4WCrrleZp3nEvfdxqmp++5aM6ydCOX081cTjdyuVEVH+gZgYqR289k9HJ3t+3zN/N53fI8XctkWj/7slzWQanUNkwvmrdt3cjlOgY0MGoEKkbqoFTS4YMHPb123rY17zg6iSKd1GoDn/N6Nqs3CgXdLBQGPgYwCAIVI3MSRWq+915i55+37Va3wlwqlVg5cHUwKIWR+dL3Ez3/Sa2mwwcP1HScV90HjUai5cHso4aKkWk6zlBNd9PmLEtveJ4WSqWki4IZRaBiJF6Gofbv30+6GJeat20tVirnBsEAE2jyYyQOy+Wki9DWSa2m/fv3dZRwlwRmDzVUjEQjlep5ylOS3qpWdd11ky4GZgQ1VBj3olKZijCVpGdMrYJBBCqMO6pUki5Cz05qNb0Mw6SLgRlBoMK4F1MUqNJ0fQFgshGoMOrsev1pwUYrMIVAhVHTWNujyQ9TGOWHMXGjocbSUtLFGMjbOzvMS8XQqKHCmGnrOz2LZj9MIFBhzLPvfjfpIgzsmGY/DKDJDyOiKNLtr35VNw4Oki7KQOZtW1YfdxIALkMNFUb4vq+DmzeTLsbATmq1vm7NAlyGQIURvu/r46OjpIsxFEb7MSwCFQM7iSIdB4H+ZW1NtVpN3zk40E/u3k26WAN7wcAUhnQ96QJg8r0MQx0HgY5/ccfS4+3tc88fvvtu67+/trenf71zR7/05Mm4izk0RvoxLAalcKmXYajDcrmnjU4+WljQd84MRlnS1IbqEh8HDIEmP845iSJ94bqv9gvd2OhpGelPLozsNyX95pMnemxZIyrl6FBLxTAIVLS8qFS0n8m81qQfRFNSutnUD+7cGb5gY0Q/KoZBoELSq5rZ069/faCNTX67w3LTbzx5om/dvq2jW7eGKd7YPPv006SLgClGoELScBstf/PatY7Pf/L8ud4/PNSPpmAGwOd7e0kXAVOMQIWOfH+ou5O+s7enD7q85qd6NQPgW7dva3+C+1bv/OxnCpmPigERqDCy5d7fWpZ6iclPnj9XutnU31iWXiwsDH1e0/7v3j0F9KNiQAQqjKwQervZ1D/02KRvSvqzZlO/cnAwccH6b8+e6cff/77iRiPpomAKEagYqrl/1vt7e/r7Pkb1zwbrRwsLarz1lpFyDOr49m19vLene599pqbj6KBUIljRFyb2Q/W5OaPH+8GdO/rGgJP6P5Dk3bun39rfH/vOVacLFD6Q9E+/+NmcZel2uayb3B0VPSBQoS9c18jc07OGCdVTvyvpj999V7/x+ee6eXhopmCX2LcsfbPZ1A/P/Oxiya9ns3rT9zXvOCMrB6YfTX6M5NYfv/PkiX58546+MsQxvifp9x4/1juHh8pK+vbSkv7jnXeMzRL437t39dHCgpwLYSpJe/funfv/4+1t7WcyU31XAoweNVToZRhq//79kRz7xcKC/mRuTp88f2782B9I+oqkD2xbbx4f69clXbvefr+f2smJHs/P63u1mn6oV3247fynbeuX2/Qtv7m+ThcALkWgQtJomv1n/ejuXX1rb08/HdkZzOrWWUGo4jI0+SFJWiiVRnr89/f29Nnt2/rzHuerJqnbIgVJerayoiPfH3VRMGWooaLlaS6nF1tbIz/PvmXp46Ojc1v+TZJP797V+z0uQeX20ziLQEVL3GhoP5MxNi+1m6dLS/q7kxP9RbPZsT9znP5wYUF/2UfQc3M/nEWTHy1zqZQWKxXNjWmt/WK9rj9qNvXfCwv65N49/dpYztpev2EqvVoUcTDi7hJMD2qoeM2R7+vZykoi5366tKR/vnZNf7W3p/8a0zktSd++e1e/P+BOU3OWpRQrqiACFW0kGaqnni4taXdxUX/9+HHXaU6DsCT9qWXpD46Ohl6Vxag/JAIVHRz5vp573kCbTo/C06UlRYuL+vejI/3jz3+uptR3LfYDvdoQ+2uLi/rVx4+Nle1mPq83GfW/8ghUdPQyDPWF605MqLbzP7bd8fnU/r4W6/WRnf9aOq232Uf1yiNQ0dVJFOlpLqeXu7tJF2WiccdUMMqPruYdR28FgW7m80kXBZhoBCp6MpdK6U3f1+Lm5timVU0TrgkkAhV9upHLyYoi3VheTrooE4XVUpAIVAzgdAHA4uam5rsMBl0VBCokAhVDuJHL6e0w1K1i8co3eW+4btJFwARglB9GnESRDkolHW1sJF2UsWOlFE5RQ4UR846jN31f1qNHV242wBuel3QRMCGooWIkrkqNdd629XYYai6VSroomAAEKkbqJIr0pe/ry3J54ldbDYL9UHEWgYqxOfJ9HZbLM7Piig1RcBGBirE7iSIdlst6UamMbTNr0whTXIZARaJeVCo6qlT0olKZii6BedvWYqVCMx+XIlAxMV6Gob70fR0HwcR1C8xZlt7wvJHfzBDTjUDFRDqJIh0HgV4EgY6DILGugXnb1s1CQbc8j5F8dEWgYiqcRJFehqGOw/BVDTYMR9ZFcC2d1nXX1RuFAk179IVAxVQ7DoJXYRtFihsNvTyzyfPx9nbb911Lp1s1zuuuq/lUStcyGV1nCSmGQKACgCEsPQUAQwhUADCEQAUAQwhUADCEQAUAQwhUADCEQAUAQwhUADCEQAUAQwhUADDketIFAM4Kw/DcIwiCpIsE9IxAHSFTYeA4jhzHMXKsSRNFkXzfVxAECsNQzQF3kIqiSFEUtX1+kGsYhqEaHW4PnclklJrALf3CMJTjOBNZtpkXY2QkGXtYlhUvLy/Hm5ubSf9aRhWLxY6/t6njFIvFvsuWzWY7HrNarfZ9TNPq9Xq8ubkZF4vFOJvNxpZlTUzZriJqqFOi2Wxqa2tLW1tbSqfT8n1fGfbqvLLCMFQul1NtSu/JNasYlJpCu7u7un//vnzfT7ooSEij0SBMJxCBOsVWVlYIVWCCEKhTzvO8joMxAMaHQJ1yzWZTJe7ECUwEBqUSVCwW2z7XaDRaczG7TSXa2NhQuVxmmgyQMAI1Qb3ULBuNhgqFgra2tjq+rlKpqFAodDxOpVJpzffcPXPf+3Q6LcdxlMvllMvljATz2XNd5LqucrnczM9SOF2YEIahoii69Msxm80qk8m0rkk7F/9WunXznM7t7eVYMCjpeVuzTF3mlvaqXq/Htm0PNM+yXq/HxWKxNT+x28OyrLhYLMb1er3v37ffc9m23XWuZ68mZR7qzs5OnM/nu/57tbse6+vrl5al32OZuKboH1d3hEz+Ya+urvYdGDs7O3E6nR7oQ2fbdryzs9Nz+XZ2dgYKEVPXKOlArVarxn7/fD7/WlkI1OnAoNSU6LcZHoahXNc917TvR61Wk+u6lzbZL/J9X/fv37/y8yJN/f4bGxsdu28wuehDnRL9zDc9DdNB18WfajabrVBttw4+CAKtrKwMdZ5xiKKo770VOq3jv8h1XWWzWW1vb/dZssudhqrrukaOhzFJuoo8y2So6ZXP57se6+wa/0Gb+e0e2Wz20nLV6/We+0sHffSqW5N/FI+LfajVatXo8ZeXl3v+WxrFNUX/qKEmqNto62mtqltT0rKs1ghxqVTq2szP5/NyXVeO47R2e+pUs9re3lalUnltFNrzvJ5qwbZtnzvfxVkGs6JdLfV0JN9xHGUyGQVBoCiKtLGx0fF4Z2d2ZLPZc881Go2O1zCdTjONLglJJ/os05hqSmcHXDrVGC3LarsL0fr6esdzXKylPnr0qGu5bNtue75qtdp10KefP89JqKHGcRxvbm62rtf6+nrH2RI7Oztda/idrt8g78NoEagjNI4PtW3brQ/t6Ye53WNtba1jedfW1jq+/9GjRz2/Np1O9zT1qlv3RK8mJVDjOD53nbrp9kVGoE4XmvxTzLIsVSqVVtOuUql0fO1pc7OdTCYjy7LaNuODIGiNPnc6l/RqEK2XJucsNkv72ch6VjcOv6oI1Cll27Yqlcq51UadVs80m019+OGHQ53z7BSqTn2uy8vLM78KqpsoilSpVFqrpC7DCP7sIVCnjGVZ8jxPnue9VrvrZc7oMHo9/lUOijAM5XleT9OnTE2xwuQgUKdMs9lUoVC4tKk87LxTUyaxdprP5/ueLO95Xl+zEXzfn4o5uRgdAjVBcRy/9rNGoyHHcTqGY6lUunSif6f+z3E6XVgwSRzH6btM/fTvVioVwhTshzppUqmUPM/r+JqNjY1LB5cmpWZ4FW/93O3fDFcDgTqBPM+TZVkdX3PZooBugfro0SPFr6bKDfQ4G5QXJ5qftbW1NfL+3EkShmHHxRf5fF7ValX1el1xHGtnZ0fValVra2uybXuMJcWoEagTqJda6vb29ms1wW5N2lwu19P69F5eM85zTbpOXx7FYlG+78t13VYXwun+p57njWza1Cxc12lEoE6oXmqpFwdZcrlcxxrP7u6uXNdtO42n0Wi0PuTdapjdBnhqtZocx2m7qUsQBMpkMjOxBLXTdLWkumG4eWMyCNQJ1UsttVarvfbB6fae3d1dvffee8rlciqXywqCQOVyWYVCQY7j6OHDh61dpjp9KB3HUT6f73iuZrOplZUVpVKpVo0sl8vJcRx9+OGHMxGmUufJ+aVSqW1tMYqikd1gcWtrS47jyPM8lUoleZ4n13UnbrBw5ox9bdYVoi5LF3vRbdNiy7JeW+JpcrepdjvIx/F07TY1yg2md3Z2Or7Otu14dXU1LhaLcbFYjFdXV3v+N2q3hLRerw90PdvtHAYzqKFOuG47UjWbTZXL5XM/q1QqXbsLerWystK2eZ9KpWha6lWzPp1Ot32+Vqvp4cOHevDggR48eKCHDx8OXTtPpVIdBwaRDAJ1whUKha4jweVy+Vyz0nEcBUFgLFQrlUrbpmkul9P6+rqR80yzi19q48DN9iYPgToFeqmlXuw7zWQyiqJo6FpMNptVFEUd+wkLhYKq1aqxAJ9GruuO/YvFdV2trq6O9ZzojECdAr3UUjc2Nl6rRaZSKQVBoPX19b7nO6bTaVWrVQVB0NOKodPZA8VisedgXV1dnalAKBQK2tzc7PlaW5al5eXloc5ZLpe1trZ2pb/MJslcHF+y/hFGdKtZ9tNkC4Kg6wqkbqO4YRjK932FYfjaPeJt224tz8zlckNN92k0Gq2dli5Ovzp7jtPA7/R79XqNuh1nkBFu3/c7jsKfzoxo994gCF67O0E2mz13DRqNRsd+6E7nOKvTNZfUumOA67oTs6JuFhGoAGAITX4AMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBDCFQAMIRABQBD/h+fh1Gb7+ZNngAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: rhsso-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: rhsso-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: rhsso-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: PROFILE
                  value: RHSSO
                - name: OPERATOR_NAME
                  value: rhsso-operator
                - name: SSO_QUARTER
                  value: 2024_Q3
                - name: SSO_VER
                  value: 7.6.11
                - name: RELATED_IMAGE_RHSSO_OPENJDK
                  value: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:710c0a0636973162b814b050b039a496afb792356e4839818fb46ecfad403bd4
                - name: RELATED_IMAGE_RHSSO_OPENJ9
                  value: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:710c0a0636973162b814b050b039a496afb792356e4839818fb46ecfad403bd4
                - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
                  value: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:81122cb34e5d927ba20d4e0fc4165acfc70382dbe0679cc8ee568bf048e601d7
                - name: RELATED_IMAGE_RHSSO_INIT_CONTAINER
                  value: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:81122cb34e5d927ba20d4e0fc4165acfc70382dbe0679cc8ee568bf048e601d7
                image: registry.redhat.io/rh-sso-7/sso7-rhel8-operator@sha256:369cc19c3c6340978208389499775f687ea752e792c5bd8f5a689571f14b84da
                imagePullPolicy: Always
                name: rhsso-operator
                resources: {}
              serviceAccountName: rhsso-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - list
          - get
          - create
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - list
          - get
          - create
          - update
          - watch
          - delete
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - list
          - get
          - create
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - list
          - get
          - create
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - list
          - get
          - create
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          - prometheusrules
          - podmonitors
          verbs:
          - list
          - get
          - create
          - update
          - watch
        - apiGroups:
          - integreatly.org
          resources:
          - grafanadashboards
          verbs:
          - get
          - list
          - create
          - update
          - watch
        - apiGroups:
          - apps
          resourceNames:
          - rhsso-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - get
          - list
          - create
          - update
          - watch
        - apiGroups:
          - keycloak.org
          resources:
          - keycloaks
          - keycloaks/status
          - keycloaks/finalizers
          - keycloakrealms
          - keycloakrealms/status
          - keycloakrealms/finalizers
          - keycloakclients
          - keycloakclients/status
          - keycloakclients/finalizers
          - keycloakbackups
          - keycloakbackups/status
          - keycloakbackups/finalizers
          - keycloakusers
          - keycloakusers/status
          - keycloakusers/finalizers
          verbs:
          - get
          - list
          - update
          - watch
        serviceAccountName: rhsso-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Keycloak
  - Identity
  - Access
  links:
  - name: Documentation
    url: https://access.redhat.com/products/red-hat-single-sign-on
  - name: Keycloak
    url: https://www.keycloak.org/
  maintainers:
  - email: customerservice@redhat.com
    name: Red Hat Customer Service
  maturity: stable
  provider:
    name: Red Hat
  version: 7.6.11-opr-001
  replaces: rhsso-operator.7.6.10-opr-001
  skips:
  - rhsso-operator.7.6.0-opr-001
  relatedImages:
  - name: sso7-rhel8-operator-369cc19c3c6340978208389499775f687ea752e792c5bd8f5a689571f14b84da-annotation
    image: registry.redhat.io/rh-sso-7/sso7-rhel8-operator@sha256:369cc19c3c6340978208389499775f687ea752e792c5bd8f5a689571f14b84da
  - name: rhsso-operator
    image: registry.redhat.io/rh-sso-7/sso7-rhel8-operator@sha256:369cc19c3c6340978208389499775f687ea752e792c5bd8f5a689571f14b84da
  - name: rhsso_openjdk
    image: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:710c0a0636973162b814b050b039a496afb792356e4839818fb46ecfad403bd4
  - name: rhsso_openj9
    image: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:710c0a0636973162b814b050b039a496afb792356e4839818fb46ecfad403bd4
  - name: keycloak_init_container
    image: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:81122cb34e5d927ba20d4e0fc4165acfc70382dbe0679cc8ee568bf048e601d7
  - name: rhsso_init_container
    image: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:81122cb34e5d927ba20d4e0fc4165acfc70382dbe0679cc8ee568bf048e601d7
