apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: addon-params-secret
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: addon-managed-api-service-parameters
    stringData:
      addon-managed-api-service: ${QUOTA}
      sts-role-arn: ${StsRoleARN}
parameters:
  - name: QUOTA
    # QUOTA value is per 100,000
    value: "1"
  - name: StsRoleARN
    value: "arn:aws:iam::485026278258:role/12345"