apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: addon-params-secret
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: addon-managed-api-service-parameters
    stringData:
      addon-managed-api-service: ${QUOTA}
      custom-domain_domain: ${DOMAIN}
      custom-smtp-username: ${USERNAME}
      custom-smtp-address: ${HOST}
      custom-smtp-password: ${PASSWORD}
      custom-smtp-port: ${PORT}
      custom-smtp-from_address: ${FROM}
      sts-role-arn: ${StsRoleARN}
parameters:
  - name: QUOTA
    # QUOTA value is per 100,000
    value: "1"
  - name: DOMAIN
    value: ""
  - name: USERNAME
    value: "dummy"
  - name: HOST
    value: "devshift.org"
  - name: PASSWORD
    value: "Password1"
  - name: PORT
    value: "567"
  - name: FROM
    value: "test@example.com"
  - name: StsRoleARN
    value: "arn:aws:iam::485026278258:role/12345"