language: go

sudo: required

go:
- 1.10.x

env:
  global:
    - OPERATOR_NAME=integreatly-operator

stages:
- test
- compile
- name: push
  if: fork = false AND branch = master

jobs:
  include:
  - stage: test
    script:
    - cd $HOME/gopath/src/github.com/integr8ly/$OPERATOR_NAME && make setup/travis code/check
    - go get github.com/mattn/goveralls
    - go install github.com/mattn/goveralls
    - go test -v -covermode=count -coverprofile=coverage.out ./...
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
  - stage: compile
    script:
    - make setup/travis image/build TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
  - stage: push
    script:
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - export TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io
    - make setup/dep setup/travis image/build/push TAG=$TAG
    - docker tag quay.io/integreatly/$OPERATOR_NAME:$TAG quay.io/integreatly/$OPERATOR_NAME:$BRANCH
    - docker push quay.io/integreatly/$OPERATOR_NAME:$BRANCH