bases:
  - ../rbac

namespace: redhat-rhmi-operator
namePrefix: rhmi-

patchesStrategicMerge:
  - patches/leader_election_role_binding.yaml
  # - patches/auth_proxy_role_binding.yaml
  - patches/role_binding.yaml
