apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: fuse-online-operator.v7.6.0
  namespace: placeholder
  annotations:
    capabilities: Seamless Upgrades
    categories: "Integration & Delivery"
    certified: "false"
    createdAt: 2019-10-08T16:12:00Z
    containerImage: registry.redhat.io/fuse7/fuse-online-operator
    support: Syndesis
    description: Manages the installation of Fuse Online, a flexible and customizable
      open source platform that provides core integration capabilities as a service.
    repository: https://github.com/syndesisio/syndesis/
    alm-examples: |
      [{
          "apiVersion": "syndesis.io/v1beta1",
          "kind": "Syndesis",
          "metadata": {
            "name": "app"
          },
          "spec" : {
            "addons": {
              "todo": {
                "enabled": false
              },
              "ops": {
                "enabled": false
              },
              "jaeger": {
                "enabled": false,
                "clientOnly": true
              }
            }
          }
      }]
spec:
  displayName: Red Hat Integration - Fuse Online
  description: |2

    Fuse Online is a flexible and customizable, open source platform that provides core integration capabilities as a service.

    This operator installs as well as configures the following Fuse Online components:
    - syndesis-server
    - syndesis-meta
    - syndesis-ui
    - syndesis-db
    - syndesis-prometheus
    - syndesis-proxy
    - syndesis-oauthproxy

    ### Before you begin
    You must configure authentication to Red Hat container registry before you can import and use the Red Hat Fuse OpenShift Image Streams. Follow instruction given below to configure the registration to container registry.

    1. Log in to the OpenShift Server as an administrator, as follow:
        ```
        oc login -u system:admin
        ```
    2. Log in to the OpenShift project where you will be installing the operator.
        ```
        oc project fuse-online
        ```
    3. Create a docker-registry secret using either Red Hat Customer Portal account or Red Hat Developer Program account credentials.
        ```
        oc create secret docker-registry syndesis-pull-secret \
          --docker-server=registry.redhat.io \
          --docker-username=CUSTOMER_PORTAL_USERNAME \
          --docker-password=CUSTOMER_PORTAL_PASSWORD \
          --docker-email=EMAIL_ADDRESS
        ```
        NOTE: You need to create a docker-registry secret in every new namespace where the image streams reside and which use registry.redhat.io.

        If you do not wish to use your Red Hat account username and password to create the secret, it is recommended to create an authentication token using a [registry service account](https://access.redhat.com/terms-based-registry/).

    ### How to install
    - When the operator is installed (you have created a subscription and the operator is running in the selected namespace) and before you create a new CR of Kind Syndesis, you have to link the secret created in the previous section to the operator service account.
    ```
    oc secrets link syndesis-operator syndesis-pull-secret --for=pull
    ```

    - Create a new CR of Kind Syndesis (click the Create New button). The CR spec contains all defaults (see below).

    ### CR Defaults
    The CR definition is pretty simple and an empy CR will trigger a base installation.

    Within the addons section, users are able to enable specific addons. The available addons at the moment are:
    - camelk: enables kamelk
    - jaeger: enable jaeger
    - ops: enables monitoring, requires extra CRDs
    - todo: a simple todo application

    - When you enable Jaeger addon, you should link the previously created `syndesis-pull-secret` secret to jaeger service accounts.
    ```
    oc secrets link jaeger-operator syndesis-pull-secret --for=pull
    oc secrets link syndesis-jaeger-ui-proxy syndesis-pull-secret --for=pull
    ```

    To enable addons, set "addon_name": {"enabled": true} in the CR.
  keywords: ['camel', 'integration', 'syndesis', 'fuse', 'online']
  version: 7.6.0
  maturity: alpha
  maintainers:
  - name: Jon Anstey
    email: janstey@redhat.com
  provider:
    name: Red Hat
  labels:
    name: syndesis-operator
  selector:
    matchLabels:
      name: syndesis-operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2VhZWFlYTt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnByb2R1Y3RpY29uc18xMDE3X1JHQl9JbnRlZ3JhdGlvbiBmaW5hbCBjb2xvcjwvdGl0bGU+PGcgaWQ9IkxheWVyXzEiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PGNpcmNsZSBjbGFzcz0iY2xzLTEiIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIwLjcxIDUwKSByb3RhdGUoLTQ1KSIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTg1LjM2LDE0LjY0QTUwLDUwLDAsMCwxLDE0LjY0LDg1LjM2WiIvPjxwYXRoIGQ9Ik0zMSwzMS4zNmExLjk0LDEuOTQsMCwwLDEtMy42Mi0uODkuNDMuNDMsMCwwLDEsLjUzLS40NCwzLjMyLDMuMzIsMCwwLDAsMi44MS43QS40My40MywwLDAsMSwzMSwzMS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik03Ny42Myw0NC43NkM3Ny4xMiw0MS4zNCw3MywyMSw2Ni4zMiwyMWMtMi40NCwwLTQuNTksMy4zNS02LDYuODgtLjQ0LDEuMDYtMS4yMywxLjA4LTEuNjMsMEM1Ny4yNCwyNC4xNiw1NS44OCwyMSw1My4yOCwyMSw0My4zNCwyMSw0Ny44NCw0NS4xOCwzOSw0NS4xOGMtNC41NywwLTUuMzctMTAuNTktNS41LTE0LjcyLDIuMTkuNjUsMy4zLTEsMy41NS0yLjYxYS42My42MywwLDAsMC0uNDgtLjcyLDMuMzYsMy4zNiwwLDAsMC0zLC44OUgyNy4zMWExLDEsMCwwLDAtLjY4LjI4bC0uNTMuNTNIMjIuMjFhLjU0LjU0LDAsMCwwLS4zOC4xNmwtMy45NSwzLjk1YS41NC41NCwwLDAsMCwuMzguOTFoLjM2bDAsMEgyOS43MWMuNiw2LjI2LDEuNzUsMjIsMTYuNDIsMTcuMTlsLS4zMiw1TDQ0LjM3LDc4LjQ2YTEsMSwwLDAsMCwxLDFoNC45YTEsMSwwLDAsMCwxLTFsLS42MS0yMy4zMy0uMTUtNS44MWM2LTIuNzgsOS01LjY2LDE2LjE5LTYuNzUtMS41OSwyLjYyLTIuMDUsNi44Ny0yLjA2LDgtLjA2LDYsMi41NSw4Ljc0LDUsMTMuMjJMNjMuNzMsNzhhMSwxLDAsMCwwLC44OSwxLjMyaDQuNjRhMSwxLDAsMCwwLC45My0uNzRMNzQsNjIuNmMtNC44My03LjQzLDEuODMtMTUuMzEsMy40MS0xN0ExLDEsMCwwLDAsNzcuNjMsNDQuNzZaTTMxLDMxLjM2YTEuOTQsMS45NCwwLDAsMS0zLjYyLS44OS40My40MywwLDAsMSwuNTMtLjQ0LDMuMzIsMy4zMiwwLDAsMCwyLjgxLjdBLjQzLjQzLDAsMCwxLDMxLDMxLjM2WiIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTQ2LjEzLDUxLjA3QzMxLjQ2LDU1LjkyLDMwLjMxLDQwLjE0LDI5LjcxLDMzLjg4SDE4LjY1TDIwLjc1LDM2YTEsMSwwLDAsMCwuNjguMjhoNmMwLDUuOCwxLjEzLDIwLjIsMTQsMjAuMmEzMS4zNCwzMS4zNCwwLDAsMCw0LjQyLS4zNVoiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik01MC40MSw0OS4zNmwuMTUsNS44MWExMDguMiwxMDguMiwwLDAsMCwxNC00LjU0LDE5Ljc5LDE5Ljc5LDAsMCwxLDIuMDYtOEM1OS40Niw0My43LDU2LjQ0LDQ2LjU4LDUwLjQxLDQ5LjM2WiIvPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  links:
  - name: Red Hat Fuse Online Documentation
    url: https://access.redhat.com/documentation/en-us/red-hat-fuse
  - name: Upstream project Syndesis
    url: https://github.com/syndesisio/syndesis
  - name: Upstream Syndesis Operator
    url: https://github.com/syndesisio/syndesis/tree/master/install/operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: syndesis-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          - project.openshift.io
          resources:
          - projects
          verbs:
          - get
        - apiGroups:
          - batch
          - extensions
          resources:
          - jobs
          verbs: [get, list, create, delete, update, watch, deletecollection]
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/exec
          - services
          - endpoints
          - persistentvolumeclaims
          - configmaps
          - secrets
          - serviceaccounts
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - ""
          resources:
          - replicationcontrollers
          - replicationcontrollers/scale
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - deployments/scale
          - replicasets
          - replicasets/scale
          - statefulsets
          - statefulsets/scale
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - extensions
          resources:
          - daemonsets
          - deployments
          - deployments/scale
          - ingresses
          - networkpolicies
          - replicasets
          - replicasets/scale
          - replicationcontrollers/scale
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          resources:
          - bindings
          - events
          - limitranges
          - namespaces/status
          - pods/log
          - pods/status
          - replicationcontrollers/status
          - resourcequotas
          - resourcequotas/status
          verbs: [get, list, watch]
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - buildconfigs
          - buildconfigs/webhooks
          - builds
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - buildconfigs/instantiate
          - buildconfigs/instantiatebinary
          - builds/clone
          verbs: [create]
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - builds/details
          verbs: [update]
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - builds/log
          verbs: [get, list, watch]
        - apiGroups:
          - ""
          - apps.openshift.io
          resources:
          - deploymentconfigs
          - deploymentconfigs/scale
          - deploymentconfigs/finalizers
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - apps.openshift.io
          resources:
          - deploymentconfigrollbacks
          - deploymentconfigs/instantiate
          - deploymentconfigs/rollback
          verbs: [create]
        - apiGroups:
          - ""
          - apps.openshift.io
          resources:
          - deploymentconfigs/log
          - deploymentconfigs/status
          verbs: [get, list, watch]
        - apiGroups:
          - ""
          - image.openshift.io
          resources:
          - imagestreams
          - imagestreamimages
          - imagestreammappings
          - imagestreams/secrets
          - imagestreamtags
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - image.openshift.io
          resources:
          - imagestreamimports
          verbs: [create]
        - apiGroups:
          - ""
          - image.openshift.io
          resources:
          - imagestreams/status
          verbs: [get, list, watch]
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - template.openshift.io
          resources:
          - processedtemplates
          - templateconfigs
          - templateinstances
          - templates
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - buildlogs
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - syndesis.io
          resources:
          - "*"
          - "*/finalizers"
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - configmaps
          - secrets
          - serviceaccounts
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - ""
          resources:
          - pods/log
          verbs: [get]
        - apiGroups:
          - ""
          resources:
          - replicationcontrollers
          - replicationcontrollers/scale
          - replicationcontrollers/status
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - ""
          - build.openshift.io
          resources:
          - builds
          - buildconfigs
          - builds/details
          - buildconfigs/webhooks
          - buildconfigs/instantiatebinary
          - builds/log
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - ""
          - apps.openshift.io
          resources:
          - deploymentconfigs
          - deploymentconfigs/scale
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - apps.openshift.io
          resources:
          - deploymentconfigrollbacks
          - deploymentconfigs/instantiate
          - deploymentconfigs/rollback
          verbs: [create]
        - apiGroups:
          - ""
          - apps.openshift.io
          resources:
          - deploymentconfigs/log
          - deploymentconfigs/status
          verbs: [get, list, watch]
        - apiGroups:
          - ""
          - image.openshift.io
          resources:
          - imagestreams
          - imagestreamimages
          - imagestreammappings
          - imagestreams/secrets
          - imagestreamtags
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - ""
          - image.openshift.io
          resources:
          - imagestreams/status
          - imagestreamimports
          verbs: [get, list, watch]
        - apiGroups:
          - ""
          resources:
          - events
          verbs: [get, list]
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - ""
          - template.openshift.io
          resources:
          - processedtemplates
          - templateconfigs
          - templateinstances
          - templates
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - authorization.openshift.io
          resources:
          - roles
          - rolebindings
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs: [get, list, create, update, delete, deletecollection, watch, patch]
        - apiGroups:
          - camel.apache.org
          resources:
          - "*"
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - alertmanagers
          - prometheuses
          - servicemonitors
          - prometheusrules
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups:
          - integreatly.org
          resources:
          - grafanadashboards
          verbs: [get, list, create, update, delete, deletecollection, watch]
        - apiGroups: # For monitoring functions by operator-sdk
          - ""
          resources:
          - services
          - services/finalizers
          verbs:
          - list
          - get
          - watch
          - create
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups: # END For monitoring functions by operator-sdk
          - serving.knative.dev
          resources:
          - services
          verbs: [get, list, watch]
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels
          verbs: [get, list, watch]
      deployments:
      - name: syndesis-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: syndesis-operator
              syndesis.io/app: syndesis
              syndesis.io/type: operator
              syndesis.io/component: syndesis-operator
          template:
            metadata:
              labels:
                name: syndesis-operator
                syndesis.io/app: syndesis
                syndesis.io/type: operator
                syndesis.io/component: syndesis-operator
            spec:
              serviceAccountName: syndesis-operator
              initContainers:
              - command:
                - bash
                - -c
                - postgres -V
                image: quay.io/integreatly/delorean:rhscl-postgresql-96-rhel7_latest
                name: postgres-version
              containers:
              - name: syndesis-operator
                image: quay.io/integreatly/delorean:fuse7-fuse-online-operator_1.6
                imagePullPolicy: Always
                ports:
                - containerPort: 60000
                  name: metrics
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "syndesis-operator"
                - name: DV_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-tech-preview-fuse-dv-rhel7_1.6
                - name: OAUTH_IMAGE
                  value: registry.redhat.io/openshift4/ose-oauth-proxy:4.2
                - name: UI_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-fuse-ignite-ui_1.6
                - name: S2I_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-fuse-ignite-s2i_1.6
                - name: PROMETHEUS_IMAGE
                  value: quay.io/integreatly/delorean:openshift3-prometheus_v3.9
                - name: UPGRADE_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-fuse-ignite-upgrade_1.6
                - name: META_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-fuse-ignite-meta_1.6
                - name: PSQL_EXPORTER_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-tech-preview-fuse-postgres-exporter_1.6
                - name: SERVER_IMAGE
                  value: quay.io/integreatly/delorean:fuse7-fuse-ignite-server_1.6
  customresourcedefinitions:
    owned:
    - name: syndesises.syndesis.io
      version: v1beta1
      kind: Syndesis
      displayName: Syndesis CRD
      description: Syndesis CRD
