apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhmi-deploy
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: cloud-resource-config
      namespace: ${INSTALLATION_NAMESPACE}
    data:
      managed: >
        {"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", "postgres":"openshift"}
      workshop: >
        {"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", "postgres":"openshift"}
      self-managed: >
        {"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", "postgres":"openshift"}
      managed-api: >
        {"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", "postgres":"openshift"}
parameters:
  - name: INSTALLATION_NAMESPACE
    required: true