apiVersion: apps/v1
kind: Deployment
metadata:
  name: integreatly-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: integreatly-operator
  template:
    metadata:
      labels:
        name: integreatly-operator
    spec:
      serviceAccountName: integreatly-operator
      containers:
        - name: integreatly-operator
          # Replace this with the built image name
          image: quay.io/integreatly/integreatly-operator:v1.7.1
          command:
          - integreatly-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "integreatly-operator"
