apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"apps.3scale.net/v1alpha1","kind":"APIManager","metadata":{"name":"example-apimanager"},"spec":{"wildcardDomain":"example.com"}},
      {"apiVersion":"apps.3scale.net/v1alpha1","kind":"APIManager","metadata":{"name":"example-apimanager-ha"},"spec":{"highAvailability":{"enabled":true},"wildcardDomain":"example.com"}},
      {"apiVersion":"apps.3scale.net/v1alpha1","kind":"APIManager","metadata":{"name":"example-apimanager-s3"},"spec":{"system":{"fileStorage":{"simpleStorageService":{"configurationSecretRef":{"name":"aws-auth"}}}},"wildcardDomain":"\u003cdesired-domain\u003e"}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"API","metadata":{"labels":{"environment":"testing"},"name":"example-api"},"spec":{"description":"api01","integrationMethod":{"apicastHosted":{"apiTestGetRequest":"/","authenticationSettings":{"credentials":{"apiKey":{"authParameterName":"user-key","credentialsLocation":"headers"}},"errors":{"authenticationFailed":{"contentType":"text/plain;
      charset=us-ascii","responseBody":"Authentication failed","responseCode":403},"authenticationMissing":{"contentType":"text/plain;
      charset=us-ascii","responseBody":"Authentication Missing","responseCode":403}},"hostHeader":"","secretToken":"MySecretTokenBetweenApicastAndMyBackend_1237120312"},"mappingRulesSelector":{"matchLabels":{"api":"api01"}},"privateBaseURL":"https://echo-api.3scale.net:443"}}}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"Binding","metadata":{"name":"example-binding"},"spec":{"APISelector":{"matchLabels":{"environment":"testing"}},"credentialsRef":{"name":"ecorp-tenant-secret"}}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"Limit","metadata":{"labels":{"api":"api01"},"name":"plan01-metric01-day-10"},"spec":{"description":"Limit
      for metric01 in plan01","maxValue":10,"metricRef":{"name":"metric01"},"period":"day"}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"MappingRule","metadata":{"labels":{"api":"api01"},"name":"metric01-get-path01"},"spec":{"increment":1,"method":"GET","metricRef":{"name":"metric01"},"path":"/path01"}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"Metric","metadata":{"labels":{"api":"api01"},"name":"metric01"},"spec":{"description":"metric01","incrementHits":false,"unit":"hit"}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"Plan","metadata":{"labels":{"api":"api01"},"name":"example-plan"},"spec":{"approvalRequired":false,"costs":{"costMonth":0,"setupFee":0},"default":true,"limitSelector":{"matchLabels":{"plan":"plan01"}},"trialPeriod":0}},
      {"apiVersion":"capabilities.3scale.net/v1alpha1","kind":"Tenant","metadata":{"name":"example-tenant"},"spec":{"email":"admin@example.com","masterCredentialsRef":{"name":"system-seed"},"organizationName":"Example.com","passwordCredentialsRef":{"name":"ecorp-admin-secret"},"systemMasterUrl":"https://master.example.com","tenantSecretRef":{"name":"ecorp-tenant-secret","namespace":"operator-test"},"username":"admin"}}]'
    capabilities: Full Lifecycle
    categories: Integration & Delivery
    certified: "false"
    containerImage: quay.io/integreatly/delorean:3scale-amp2-3scale-rhel7-operator_latest
    createdAt: "2019-05-30T22:40:00Z"
    description: 3scale Operator to provision 3scale and publish/manage API
    repository: https://github.com/3scale/3scale-operator
    support: Red Hat, Inc.
    tectonic-visibility: ocs
  name: 3scale-operator.v0.5.3
  namespace: placeholder
spec:
  customresourcedefinitions:
    owned:
    - description: API Manager
      displayName: API Manager
      kind: APIManager
      name: apimanagers.apps.3scale.net
      resources:
      - kind: DeploymentConfig
        name: ""
        version: apps.openshift.io/v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: route.openshift.io/v1
      - kind: ImageStream
        name: ""
        version: image.openshift.io/v1
      specDescriptors:
      - description: Wildcard domain as configured in the API Manager object
        displayName: Wildcard Domain
        path: wildcardDomain
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      statusDescriptors:
      - description: API Manager Deployment Configs
        displayName: Deployments
        path: deployments
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      version: v1alpha1
    - description: API
      displayName: API
      kind: API
      name: apis.capabilities.3scale.net
      version: v1alpha1
    - description: Binding
      displayName: Binding
      kind: Binding
      name: bindings.capabilities.3scale.net
      version: v1alpha1
    - description: Limit
      displayName: Limit
      kind: Limit
      name: limits.capabilities.3scale.net
      version: v1alpha1
    - description: MappingRule
      displayName: MappingRule
      kind: MappingRule
      name: mappingrules.capabilities.3scale.net
      version: v1alpha1
    - description: Metric
      displayName: Metric
      kind: Metric
      name: metrics.capabilities.3scale.net
      version: v1alpha1
    - description: Plan
      displayName: Plan
      kind: Plan
      name: plans.capabilities.3scale.net
      version: v1alpha1
    - description: Tenant
      displayName: Tenant
      kind: Tenant
      name: tenants.capabilities.3scale.net
      version: v1alpha1
  description: |
    The 3scale Operator creates and maintains the Red Hat 3scale API Management on OpenShift in various deployment configurations.

    3scale API Management makes it easy to manage your APIs.
    Share, secure, distribute, control, and monetize your APIs on an infrastructure platform built for performance, customer control, and future growth.

    ### Supported Features
    * **Installer** A way to install a 3scale API Management solution, providing configurability options at the time of installation
    * **Upgrade** Upgrade from previously installed 3scale API Management solution
    * **Reconcilliation** Tunable CRD parameters after 3scale API Management solution is installed
    * **Capabilities** Ability to define 3scale API definitions and set them into a 3scale API Management solution

    ### Documentation
    [3scale api management](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management)
    [Deploying 3scale using the operator](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.8/html/installing_3scale/install-threescale-on-openshift-guide#deploying-threescale-using-the-operator)

    ### Getting help
    If you encounter any issues while using 3scale operator, you can create an issue on our [Github repo](https://github.com/3scale/3scale-operator) for bugs, enhancements, or other requests.

    ### Contributing
    You can contribute by:

    * Raising any issues you find using 3scale Operator
    * Fixing issues by opening [Pull Requests](https://github.com/3scale/3scale-operator/pulls)
    * Talking about 3scale Operator

    All bugs, tasks or enhancements are tracked as [GitHub issues](https://github.com/3scale/3scale-operator/issues).

    ### License
    3scale Operator is licensed under the [Apache 2.0 license](https://github.com/3scale/3scale-operator/blob/master/LICENSE)
  displayName: Red Hat Integration - 3scale
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnByb2R1Y3RpY29uc18xMDE3X1JHQl9BUEkgZmluYWwgY29sb3I8L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0yMC43MSA1MCkgcm90YXRlKC00NSkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiwxNC42NEE1MCw1MCwwLDAsMSwxNC42NCw4NS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik01MC4yNSwzMC44M2EyLjY5LDIuNjksMCwxLDAtMi42OC0yLjY5QTIuNjUsMi42NSwwLDAsMCw1MC4yNSwzMC44M1pNNDMuMzYsMzkuNGEzLjM1LDMuMzUsMCwwLDAsMy4zMiwzLjM0LDMuMzQsMy4zNCwwLDAsMCwwLTYuNjdBMy4zNSwzLjM1LDAsMCwwLDQzLjM2LDM5LjRabTMuOTIsOS44OUEyLjY4LDIuNjgsMCwxLDAsNDQuNiw1MiwyLjcsMi43LDAsMCwwLDQ3LjI4LDQ5LjI5Wk0zMi42MywyOS42NWEzLjI2LDMuMjYsMCwxLDAtMy4yNC0zLjI2QTMuMjYsMy4yNiwwLDAsMCwzMi42MywyOS42NVpNNDAuNTMsMzRhMi43NywyLjc3LDAsMCwwLDAtNS41MywyLjc5LDIuNzksMCwwLDAtMi43NiwyLjc3QTIuODUsMi44NSwwLDAsMCw0MC41MywzNFptMS43Ni05LjMxYTQuNCw0LjQsMCwxLDAtNC4zOC00LjRBNC4zNyw0LjM3LDAsMCwwLDQyLjI5LDI0LjcxWk0zMi43OCw0OWE3LDcsMCwxLDAtNy03QTcsNywwLDAsMCwzMi43OCw0OVptMzIuMTMtNy43YTQuMjMsNC4yMywwLDAsMCw0LjMsNC4zMSw0LjMxLDQuMzEsMCwxLDAtNC4zLTQuMzFabTYuOSwxMC4wNmEzLjA4LDMuMDgsMCwxLDAsMy4wOC0zLjA5QTMuMDksMy4wOSwwLDAsMCw3MS44MSw1MS4zOFpNNzMuOSwzNC43N2E0LjMxLDQuMzEsMCwxLDAtNC4zLTQuMzFBNC4yOCw0LjI4LDAsMCwwLDczLjksMzQuNzdaTTUyLjE2LDQ1LjA2YTMuNjUsMy42NSwwLDEsMCwzLjY1LTMuNjZBMy42NCwzLjY0LDAsMCwwLDUyLjE2LDQ1LjA2Wk01NSwyMmEzLjE3LDMuMTcsMCwwLDAsMy4xNi0zLjE3QTMuMjMsMy4yMywwLDAsMCw1NSwxNS42MywzLjE3LDMuMTcsMCwwLDAsNTUsMjJabS0uNDcsMTAuMDlBNS4zNyw1LjM3LDAsMCwwLDYwLDM3LjU0YTUuNDgsNS40OCwwLDEsMC01LjQ1LTUuNDhaTTY2LjI1LDI1LjVhMi42OSwyLjY5LDAsMSwwLTIuNjgtMi42OUEyLjY1LDIuNjUsMCwwLDAsNjYuMjUsMjUuNVpNNDUuNyw2My4xYTMuNDIsMy40MiwwLDEsMC0zLjQxLTMuNDJBMy40MywzLjQzLDAsMCwwLDQ1LjcsNjMuMVptMTQsMTEuMTlhNC40LDQuNCwwLDEsMCw0LjM4LDQuNEE0LjM3LDQuMzcsMCwwLDAsNTkuNzMsNzQuMjlaTTYyLjMsNTAuNTFhOS4yLDkuMiwwLDEsMCw5LjE2LDkuMkE5LjIyLDkuMjIsMCwwLDAsNjIuMyw1MC41MVpNNTAuMSw2Ni43N2EyLjY5LDIuNjksMCwxLDAsMi42OCwyLjY5QTIuNywyLjcsMCwwLDAsNTAuMSw2Ni43N1pNODEuMjUsNDEuMTJhMi43LDIuNywwLDAsMC0yLjY4LDIuNjksMi42NSwyLjY1LDAsMCwwLDIuNjgsMi42OSwyLjY5LDIuNjksMCwwLDAsMC01LjM3Wk00NC40OSw3Ni40N2EzLjczLDMuNzMsMCwwLDAtMy43MywzLjc0LDMuNzcsMy43NywwLDEsMCwzLjczLTMuNzRaTTc5LjA2LDU2LjcyYTQsNCwwLDEsMCw0LDRBNCw0LDAsMCwwLDc5LjA2LDU2LjcyWm0tNiwxMS43OEEzLjA5LDMuMDksMCwwLDAsNzAsNzEuNmEzLDMsMCwwLDAsMy4wOCwzLjA5LDMuMDksMy4wOSwwLDAsMCwwLTYuMTlaTTI4LjMsNjhhNC4xNiw0LjE2LDAsMCwwLTQuMTQsNC4xNUE0LjIxLDQuMjEsMCwwLDAsMjguMyw3Ni4zYTQuMTUsNC4xNSwwLDAsMCwwLTguM1ptLTguMjItOWEzLDMsMCwxLDAsMywzQTMuMDUsMy4wNSwwLDAsMCwyMC4wOCw1OVptMS44NC05Ljc0YTMsMywwLDEsMCwzLDNBMy4wNSwzLjA1LDAsMCwwLDIxLjkxLDQ5LjIyWk0yMi4zNyw0MmEzLjI0LDMuMjQsMCwxLDAtMy4yNCwzLjI2QTMuMjYsMy4yNiwwLDAsMCwyMi4zNyw0MlpNNDMuMTEsNzAuMmEzLjgsMy44LDAsMCwwLTMuODEtMy43NCwzLjczLDMuNzMsMCwwLDAtMy43MywzLjc0QTMuOCwzLjgsMCwwLDAsMzkuMyw3NCwzLjg3LDMuODcsMCwwLDAsNDMuMTEsNzAuMlpNMzcuNTYsNTguNDNhNC42OCw0LjY4LDAsMCwwLTQuNjItNC42NCw0LjYzLDQuNjMsMCwwLDAtNC42Miw0LjY0LDQuNTgsNC41OCwwLDAsMCw0LjYyLDQuNjRBNC42Myw0LjYzLDAsMCwwLDM3LjU2LDU4LjQzWk0yMy4xMSwzMy44MmEyLjUyLDIuNTIsMCwxLDAtMi41MS0yLjUyQTIuNTMsMi41MywwLDAsMCwyMy4xMSwzMy44MloiLz48L2c+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: 3scale-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: threescale-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: threescale-operator
            spec:
              containers:
              - command:
                - 3scale-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: threescale-operator
                - name: BACKEND_IMAGE
                  value: quay.io/integreatly/delorean:3scale-amp2-backend-rhel7_latest
                - name: APICAST_IMAGE
                  value: quay.io/integreatly/delorean:3scale-amp2-apicast-gateway-rhel8_latest
                - name: SYSTEM_IMAGE
                  value: quay.io/integreatly/delorean:3scale-amp2-system-rhel7_latest
                - name: ZYNC_IMAGE
                  value: quay.io/integreatly/delorean:3scale-amp2-zync-rhel7_latest
                - name: SYSTEM_MEMCACHED_IMAGE
                  value: quay.io/integreatly/delorean:3scale-amp2-memcached-rhel7_latest
                - name: BACKEND_REDIS_IMAGE
                  value: quay.io/integreatly/delorean:rhscl-redis-32-rhel7_latest
                - name: SYSTEM_REDIS_IMAGE
                  value: quay.io/integreatly/delorean:rhscl-redis-32-rhel7_latest
                - name: SYSTEM_MYSQL_IMAGE
                  value: quay.io/integreatly/delorean:rhscl-mysql-57-rhel7_latest
                - name: SYSTEM_POSTGRESQL_IMAGE
                  value: quay.io/integreatly/delorean:rhscl-postgresql-10-rhel7_latest
                - name: ZYNC_POSTGRESQL_IMAGE
                  value: quay.io/integreatly/delorean:rhscl-postgresql-10-rhel7_latest
                image: quay.io/integreatly/delorean:3scale-amp2-3scale-rhel7-operator_latest
                name: 3scale-operator
                resources: {}
              serviceAccountName: 3scale-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - replicationcontrollers
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          - bindings/finalizers
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - 3scale-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - '*'
        - apiGroups:
          - image.openshift.io
          resources:
          - imagestreams
          - imagestreams/layers
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/status
          verbs:
          - get
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - get
          - list
          - create
          - update
          - watch
          - delete
        - apiGroups:
          - apps.3scale.net
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - capabilities.3scale.net
          resources:
          - '*'
          - bindings
          - metrics
          - plans
          - limits
          - mappingrules
          - tenants
          verbs:
          - '*'
        serviceAccountName: 3scale-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - 3scale
  - API
  links:
  - name: GitHub
    url: https://github.com/3scale/3scale-operator
  - name: Documentation
    url: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.8/html/installing_3scale/install-threescale-on-openshift-guide#deploying-threescale-using-the-operator
  maintainers:
  - email: eastizle+3scaleoperator@redhat.com
    name: 3scale
  - email: msoriano+3scaleoperator@redhat.com
    name: 3scale
  maturity: stable
  provider:
    name: Red Hat
  relatedImages:
  - image: registry.stage.redhat.io/3scale-amp2/apicast-gateway-rhel8@sha256:52013cc8722ce507e3d0b066a8ae4edb930fb54e24e9f653016658ad1708b5d7
    name: apicast-gateway-rhel8
  - image: registry.stage.redhat.io/3scale-amp2/backend-rhel7@sha256:bd626295c55a7815a816d7049fba1febdec6a3305dee2a3292e92a26d56036b0
    name: backend-rhel7
  - image: registry.stage.redhat.io/3scale-amp2/system-rhel7@sha256:a934997501b41be2ca2b62e37c35bd334252b5e2ed28652c275bd1de8a9d324a
    name: system-rhel7
  - image: registry.stage.redhat.io/3scale-amp2/zync-rhel7@sha256:fd539b44f0fd70726fa3ed42417bf9084a95c1d8f4d01579d4cea78e9c90110c
    name: zync-rhel7
  - image: registry.stage.redhat.io/3scale-amp2/memcached-rhel7@sha256:2be57d773843135c0677e31d34b0cd24fa9dafc4ef1367521caa2bab7c6122e6
    name: memcached-rhel7
  - name: redis-32-rhel7
    value: registry.redhat.io/rhscl/redis-32-rhel7@sha256:a9bdf52384a222635efc0284db47d12fbde8c3d0fcb66517ba8eefad1d4e9dc9
  - name: mysql-57-rhel7
    value: registry.redhat.io/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
  - name: postgresql-10-rhel7
    value: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:de3ab628b403dc5eed986a7f392c34687bddafee7bdfccfd65cecf137ade3dfd
  replaces: 3scale-operator.v0.5.0
  version: 0.5.3
