---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoam-operator
subjects:
- kind: ServiceAccount
  name: rhmi-operator
  namespace: redhat-rhoam-operator
roleRef:
  kind: Role
  name: rhmi-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoam-operator
subjects:
  - kind: ServiceAccount
    name: rhmi-operator
    namespace: redhat-rhoam-operator
roleRef:
  kind: ClusterRole
  name: rhmi-operator
  apiGroup: rbac.authorization.k8s.io
  