apiVersion: integreatly.org/v1alpha1
kind: RHMI
metadata:
  name: INSTALLATION_NAME
  annotations:
    in_prow: IN_PROW
spec:
  type: INSTALLATION_TYPE
  namespacePrefix: INSTALLATION_PREFIX-
  selfSignedCerts: SELF_SIGNED_CERTS
  useClusterStorage: 'USE_CLUSTER_STORAGE'
  operatorsInProductNamespace: OPERATORS_IN_PRODUCT_NAMESPACE
  smtpSecret: INSTALLATION_PREFIX-smtp
  deadMansSnitchSecret: INSTALLATION_PREFIX-deadmanssnitch
  pagerDutySecret: INSTALLATION_PREFIX-pagerduty
  priorityClassName: INSTALLATION_SHORTHAND-pod-priority
