apiVersion: integreatly.org/v1alpha1
kind: RHMI
metadata:
  name: INSTALLATION_NAME
spec:
  type: INSTALLATION_TYPE
  namespacePrefix: INSTALLATION_PREFIX-
  selfSignedCerts: SELF_SIGNED_CERTS
  useClusterStorage: USE_CLUSTER_STORAGE
  smtpSecret: INSTALLATION_PREFIX-smtp
