apiVersion: integreatly.org/v1alpha1
kind: Installation
metadata:
  name: INSTALLATION_NAME
spec:
  type: INSTALLATION_TYPE
  namespacePrefix: INSTALLATION_PREFIX
  selfSignedCerts: SELF_SIGNED_CERTS
