global:
  resolve_timeout: 5m
  smtp_smarthost: {{ index .Params "SMTPHost" }}:{{ index .Params "SMTPPort" }}
  smtp_from: noreply@{{ index .Params "AlertManagerRoute" }}
  smtp_auth_username: {{ index .Params "SMTPUsername" }}
  smtp_auth_password: {{ index .Params "SMTPPassword"}}
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
    - match:
        severity: critical
      receiver: critical
    - match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
      receiver: deadmansswitch
    - match:
        alertname: RHOAMApiUsageLevel1ThresholdExceeded
      receiver: BUandCustomer
    - match:
        alertname: RHOAMApiUsageLevel2ThresholdExceeded
      receiver: BUandCustomer
    - match:
        alertname: RHOAMApiUsageLevel3ThresholdExceeded
      receiver: SRECustomerBU
    - match_re:
        alertname: RHOAMApiUsageSoftLimitReachedTier[0-9]+
      receiver: BU
    - match:
        alertname: RHOAMApiUsageOverLimit
      receiver: BUandCustomer
receivers:
  - name: default
    email_configs:
      - send_resolved: true
        to: {{ index .Params "SMTPToSREAddress" }}
  - name: critical
    pagerduty_configs:
      - service_key: {{ index .Params "PagerDutyServiceKey" }}
    email_configs:
      - send_resolved: true
        to: {{ index .Params "SMTPToSREAddress" }}
  - name: deadmansswitch
    webhook_configs:
      - url: {{ index .Params "DeadMansSnitchURL" }}
  - name: BU
    email_configs:
      - send_resolved: True
        to: '{{ index .Params "SMTPToBUAddress" }}'
  - name: BUandCustomer
    email_configs:
      - send_resolved: True
        to: '{{ index .Params "SMTPToBUAddress" }}, {{ index .Params "SMTPToCustomerAddress" }}'
  - name: SRECustomerBU
    email_configs:
      - send_resolved: True
        to: '{{ index .Params "SMTPToSREAddress" }}, {{ index .Params "SMTPToBUAddress" }}, {{ index .Params "SMTPToCustomerAddress" }}'
inhibit_rules:
  - source_match:
      alertname: 'JobRunningTimeExceeded'
      severity: 'warning'
    target_match:
      alertname: 'JobRunningTimeExceeded'
      severity: 'warning'
    equal: ['alertname', 'job', 'label_cronjob_name']