apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    operatorframework.io/suggested-namespace: redhat-rhoam-operator
    alm-examples: '[]'
    capabilities: Basic Install
    categories: "Integration & Delivery"
    certified: "false"
    containerImage: quay.io/integreatly/managed-api-service:rhoam-v1.1.0
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.17"}]'
    support: RHOAM
  name: managed-api-service.v1.43.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: RHMI
        name: rhmis.integreatly.org
        version: v1alpha1
        description: RHOAM is the Schema for the RHOAM API
        displayName: RHOAM installation
        resources:
          - kind: Deployment
            name: 'rhoam-operator'
            version: v1
          - kind: Pod
            name: 'rhoam'
            version: v1
        specDescriptors:
          - description: namespacePrefix
            displayName: namespacePrefix
            path: namespacePrefix
          - description: operatorsInProductNamespace
            displayName: operatorsInProductNamespace
            path: operatorsInProductNamespace
          - description: pagerDutySecret
            displayName: pagerDutySecret
            path: pagerDutySecret
          - description: selfSignedCerts
            displayName: selfSignedCerts
            path: selfSignedCerts
          - description: deadMansSnitchSecret
            displayName: deadMansSnitchSecret
            path: deadMansSnitchSecret
          - description: type
            displayName: type
            path: type
          - description: useClusterStorage
            displayName: useClusterStorage
            path: useClusterStorage
          - description: priorityClassName
            displayName: priorityClassName
            path: priorityClassName
          - description: smtpSecret
            displayName: smtpSecret
            path: smtpSecret
          - description: pagerDutySecret
            displayName: pagerDutySecret
            path: pagerDutySecret
          - description: priorityClassName
            displayName: priorityClassName
            path: priorityClassName
          - description: selfSignedCerts
            displayName: selfSignedCerts
            path: selfSignedCerts
          - description: smtpSecret
            displayName: smtpSecret
            path: smtpSecret
          - description: type
            displayName: type
            path: type
          - description: useClusterStorage
            displayName: useClusterStorage
            path: useClusterStorage
          - description: deadMansSnitchSecret
            displayName: deadMansSnitchSecret
            path: deadMansSnitchSecret
        statusDescriptors:
          - description: The status of each of the RHMI CR
            displayName: RHMI CR Status
            path: status
  description: RHOAM integration suite of tools
  displayName: RHOAM
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAXMAAAFyCAYAAAAH5jo3AAAACXBIWXMAAG66AABuugHW3rEXAAAeWklEQVR4nO3dzW8cx5nH8acdJdlFEpKHvUrkHyBB4+tKCJmrDVv00YIDU3uykQBhTl44B1GHNVY3Bohhn1YUNpD2ZsqGdDVlSHs1BeluUrobHG6CzebFvXio6mhMc166urr6qervB2gYskROz0z1b2qerpeiLEsBAKTtJd4/AEgfYQ4AGSDMASADhDkAZOAUb2JzRVEsiMhARJbcUf1Z3J8XU35+QACPROTA/Zod999d/X9lWe7wAjfHaJaaiqIYuKAePeaTehKAPfsisueCXkN+tyzLPd6n2RHmUxRFsSIi1UFwA/Hsu2DXgN8py3KX1348wvwYVzJZdccK4Q2Yse+Cfbssy23elm8jzJ8H+JIL7zUROW/glABMd0eD3YX7Qd9fr96G+bEe+CUDpwTAz3Ak1HvbY+9dmLte+IYLcUooQF60FLMlIpt96633JsyLotDwXheRZQOnA6B9N12o9+LGafZhXhTFmuuJM9Yb6Kf7mgG5j2fPNswJcQDHZB3q2YU5IQ5giixDPZswd5N7NqiJA5jRTRfqWcw0TT7MR0anvG3gdACkZehukm6k/r4lHeZFUay7IGeIIYAmdEjjWsqllyTD3C12tcVsTQCBaellPcUx6smtZ14UhfbEvyTIAbRAy7V77h5cUpIJc62NF0WhX4GuGjgdAPnSsu3nRVFsumU/kpBEmcXN3tyiNg4gskeulm5+Fqn5nrl+OorIJwQ5gA5oOXfHzV8xzWzP3H292aE2DsCIm2VZmg11k2HuRqvs0BsHYIyWXVYsjnYxV2ZxX2cIcgAWVWWXgbVzM9Uzd0F+w8CpAMAkQ9dDN3Nj1EzPvCiKLYIcQCLmrd0YNdEzd0HO2ioAUnSlLMutrs+78545QQ4gcTcs9NA7DXOCHEAmOg/0zsKcIAeQmU4DvZMwJ8gBZKqzQI8e5m7VQ4IcQK5udLHqYtTRLIwjB9AT0cehRwtz90n1eZQHA4DuaaAvxZr6H6XM4qa+bsd4LAAwoppYFGVN9NbD3D0R1iIH0Ee6lstmjOcdo2fOXp0A+uxtt/l8q1qtmbuRK2zzBgAiL7d5Q7S1MOeGJwB8y76IDNq6IdpKmWWkTg4AeG6xzVxsq2a+5U4cAPDCpbbq58HLLG4n/U+C/lIAyMfQlVv2Qj6joGHuyit7DEMEgInul2UZdMp/6DIL48kBYLrl0OWWYD1zRq8AQC1Bp/sH6ZkzegUAapsPOTs0VJllndErAFDb26GWy21cZimKYklEdqmVA4CXR2VZDpq+dCF65hsEOQB4Ox9id6JGPXO3tO2XvIcA0Mh+WZZLTX5B0555lKUdASBzi25hQm/ePXOGIgJAUI2GKjbpmTf6FAEAfMu8GxnoxatnTq0cAFrhXTv37Zm3vmsGAPTQou/Ilto9czeu/CtaGQC0wqt37tMzp1cOAO1Z9JkV6tMzP2CSEAC06k5Zlqt1HqBWz9zVcghyAGjXJVfSnlndMkvjKacAgPB5O3OZhRufABBVrRuhdXrm9MoBIJ5FN6dnJoQ5ANg18+jBmcoszPgEgE4My7JcmOWBZ+2Z0ysHgPjmZx1zPmuYB9nWCABQ20zjzaeWWRjFAgCdmmlUyyw981qzkAAAQS3OMoFoljCnxAIA3ZraqSbMAcC+qTk8MczdkETWYgGAbjULc3rlAGDC/LTZoIQ5AKRhYh5PC/OZ1wUAALTKr2deFIVOIV3kvQEAE7zLLPTKAcCO85POZFKYUy8HAEMm3QSdFOa1d4cGALRqbC4T5gCQDq+eOTVzALDFK8yZ+QkAtozdqOLEMK+z7xwAIJraPfOZtikCAEQ1tmIyLsy5+QkABrkJnd9BmANAWk4stcy6BygAwDDCHAAyMC7MmcoPADZRZgGADNS6AQoASAhhDgAZIMwBIAOEOQBkgDAHgAwQ5gCQAcIcADJAmANABghzAMjAKd7E/Jxxx3GPRWTY9xenR2gH/UKYZ+CciLwiIhdF5MKUp3MoIg9E5KGI3BWRp31/8TJCO+i3oizL77wARVHsiMhy318c6y6LyHsicrrBeerFfN1d2KAd0A6ScK0sy43jJ0rNPEF68T4Skd81vIDF9eA+FZHPXI8O6aAdYBRhnpAz7mILcfEeV13MH/TlxUxYrHYwdrNJmESYJ0J7S1/MUAtt6h33OFzINsVsB5+NuYEKmwjzBFx2vaW5SKd61n19P5f0q5afLtrBF7SDZBDmxl12X6djm3M9My5kG2gHmIYwN+xcRxdwRS/kDym5dI52gFkQ5kbNux5R1866Cxnd0Hbwe9oBZkCYG/VhxNroNK+4r/mI78MWRqzQDvJEmBt00V04ljBULT7aAeogzA16z+A5zbnhaoiHdoA6WJvFmFnW1ZimWnfj8ci/C/F73xWRj1mkKQraAeoizI15s8Hp6MX7vls46fiFdt1NAHmnQc9Ke2Wvisgtk69cXmgHqIsyizG+F/ETETnvLrBxPaan7iJfdhe8D2s13FzRDlAXYW7Iq56nohfwazW+9j52/97nQuYibl8q7YAbobZQZjHkrOepvOVRv3zsvnL/m8fjvXusDtsWa5sojNvsITTfD8zY7eAcS+aaQpgb4rP06O0GGwt85Oqmdccx+1z4vm67kkCXoX7ODclre3GrJrpoBxcIc1Mosxji0+v7uOHpN/35tr3pZsJ29ZX+nHt8y0EuHbUDyiy2EOaG1O0ZHQYod6TQszrb0ZT2akkFKzNxx+mqHbD4li2EecJC1K1j1L5DuNDBDjjvJBDk0rN2gPEIcyQj9kga1iFBSgjzhIUYWZHSTjKxv9ZbWeBqmr61A5yMMDfkWc1TOR3gImTz3vR11Q58R8+gHYS5IT4XR5Np3yF+HjZ00Q4Ic1sIc0N8bkK922CIWIhFl2BDF+3gCe+9KYS5IQ89TmXOc9ielR1sEEYX7YAJQ7YQ5ob4XhwXau7ReCaR8dOoJ2Y7eMISuOYQ5oboxXHP83SqmZLTbmTp1/EvGqwDA9titYPbtANzWJvFmNsNxlPrhfmp6zU9cGWboeuBXXCr8TXtjb8e8OX6NODvsuCJW0cmhHMN1sCJ0Q5Yy9wewtyYu26IYpMxzmfdEXp7r9vUSScaBnx9HngufjWqzXZAicUeyiwGXTd4TodGzytnoXr5IdEO7CLMDbrlObKlTR8xrji6u7QD1ECYG/WLBlt6hfaE3lhnaAeYFWFu1FN3IXft0O1gg27QDjArwtww/Zr9yw5P79DtEcnX6m7RDjALwty4Wx1dyNUFzDrXNtAOMA1hnoDYFzIXsE20A0xCmCdCL+Rlj2Vy69LRE+e5gM2iHWAcwjwhemH9tKURBc9cr+81JoSY12Y7OKQdJIswT8zQXcQDt6N602FrGuK/ceHAFO10tNUOztMOksV0/kQ9dTMEr7u1Nl5xiyvNsubGs5EJKXcze10WFhZkMBhM/Xc7OztRzqdttANUCPPEDV1PqupNnRk5Rtf1qJYsfZzR12cN7ZWVlaP/6nH+/Pnav+P+/fuyu7t7dGjA7+3ttXKubetzO8BzhHlmnmY8Hvj7Cwuytroqq6urRyE+P++7t84Ly8vLR0dlf3//KNS3t7dF9EhUzu0AJyvKsvzOXxRFseNumgOt+XrGX3xqZUV+uLYmP3j77ahvRjkcyp+3tuRPm5vyzQw99ofuxiHQsmtlWW4cfwhugMKsH6ytyfzenvzk88+jB7kq5uflh7/6lcx/9ZX8eHv76EMFsIowhzlViP/oxg15aXHRxOl9/9Klow+Vn+zsyPdmuMEKxEaYwwwNSQ1LSyF+3KnlZZn78kv50daWFAsLtk4OvUaYw4R/3Ng4CslTy2ncqtGyj357+P7qqoGzAQhzdEx743O7u/IPV68m91ZoTf3Hn3xyVE+nl46uEebojNbGj2rQHuPDLTmqp+/syBy1dHSIMEcnNjY2jmrjRYCx4hboB9I/7+wcjYEHukCYI7qtrS25mmBZZZpT8/PyySefyNramu0TRZYIc0SlQf52B2PGY7px4waBjuiYzo9oYgT5o0ePjtZX0bVWxtGlAJaWlmSxxeGPGujinjMQA2GOKNoKcg1vXUdF11OpuxKirrCowa6H1rpDhzuBjqh0bZbjh64Qqn/FwRHiWF9fL0M6ODgoNzc3y6WlpaDvz8rKSrm1tRX8XAeDAe2II+SxcWJuE+YcbR4akCGDcWNjo1xYWGj1nPVDImSo63m3fc4cvToIc464hwaYBlkIGq6xA1F71Ds7O0HOX38P7Y8j0EGYc8Q9QgTh3t7eUe++y/dOy0QhPpT0WwVtkCPAQZhzxDtC1Mm3t7fNlCe0l64fLE2FrvNz9PI4MczZnCIQ3Z7rTbf/YpeGbpOEWx1uC6ajRHR4YJOdgG7evGlurLY+Lx0x47M9XUW3qVvpcF102mkWTtycgp55gOM9kfJrY8eeSPlqR69H05uH2qu3+l7rNwX9xtDE2toa7VS6b6cJH/TM2/CBiLxj+Px+HnnndZ2M89VXX3n//LVr147WbbFOJyX59tB1n1F9nWKinWaFbeNCu2j8AlEfikjMpayaBLGWVlIIcnGzSHXCkg+dnBSzhEQ77QfCvAHrF4iaE5HLkR5Le5u+szw1GFNaz+Tg4OBo1uhw6FfxjfmhRTvtB8K8ga5vIs3qQqTH8Q0oDcQUl47Vm7y+H0Axe+e0034gzBuYS+Q8Y3x91ZEevr3y9fX1o2BMka4Lc+fOHa8zjxXmtNN+IMwRhG8w6VC91Bei0ufuU25ZXl6OfiMU+SLMEYRvmGuvPHVaP9/c3Ozt84cNhDka096lzzA9Hb0yad3xlOj9Ah1yWBfbzCEUwhyN+c5o9O3NWuVTLtIboZRaEAJhjsZ8epc6FDGXXnnF98OJ3jlCIMzRmE/PPLdeubjauZaO6upyrRbkg23jItKFhV4L8HBfG3pOg8HAa0EtHdKXI31edYdo6mtoSY7ttA/omaMRn3qvlli0F5ujuvuQiqub6zh9oAl65j0w3+IswNc9epW59srFlVp07LyOIa/j54OBfOnxQQBUCPMeOCsin7b0NH/sEeY+vdeU6I3dumH+74OB/B9hjgYos6CRwqM8kOrU/Vn5jNJ5iTILGiLM0chLHjXz3MPc5/n5fCgCowhzNPLS4mKtH/ddAzwlPmH+PWMjWpAewhxR5TqKZVTu3zxgE2EOABkgzAEgA4Q5AGSAMEdUfZjpyCqI6AJhjka+qbmGt8+656nxCfO/ZbaCJOIjzNHINx4jN3Lvufo8v7IHo3zQLsIcjfiEUO5h7rMK4jeEORpibZYeeCIi77f0NP9ld1euXLpU62d0/e6c12fxCfN/3d2VL1s5m/bW5YEthHkP6L7xD1p6mv+kYV7zZ3RnHd0zM0d6g7fuIlvqP3d3hb45miDMIzonIp9l9px8ZjvqTVANvRxng/rsGqQbQVt6LXJsp31AmEc0JyIXMntOukLgcDisvduQ9s59NkC2zmc/T2t7oebYTvuAG6BozKf+vb6+nt0Lr9826m4ZJz1Y3x1xEOZozGfnIC21WNv7sinfD6icd15CPIQ5GvPtWebWO19bW6v9M1ovZ5VFhECYozENI591yrUkkUvvXEfnLNZc213olSMgwhxB+N7M3NzcTP4N0Fq577eMHJ4/bCDMEYRvmOuYbJ/yhCX63OuO5lG6iz8lFoRCmDfwMJHzvBfhMXSc9M2bN71+VnunqU7x16GIl2rOgK3EGppJO+0HwryB24mc591Ij+M7q1N7tSnWjvUDyDeQ9cZnrDCnnfYDYd7ArQR6PddF5Gmkx9KSgW/vXIcqpjSJSOvk+gHkU16RBh98Pmin/UCYN/SW4QvlY3eRxNQkpHR0SyprtuhwTN+12WP2yiu00/wR5g3pIlavicgvjdT8Dt3X6tdbXClxkia9c3X16lXT48+rHnmTTTa6+MCinfZAWZbfObTjoX/FweFzLCwslAcHB2UTW1tb5l57fV67u7uNntfOzg5tiqPpsXFibhPmHG0c6+vrjUJPbW9vHwWohfdoMBiUe3t7jZ/T0tIS7Y2j6UGYc8Q9tBfalAboyspKp++dfjA1/aahNjY2aIMcIQ7CnCPuEaLcUtGyS+xeuvbGQ3wglZRXOMIehDlH/EN71aHoB4P2btsOdS2F6IdHyPO2Ui7iyOIgzDm6OULUz4+H4+bmZvD6s37whAzx6ly1h0/b4wh4EOYc3R2hQ7Kio0u0t+5TV9fe8urq6tEHQ4ibmydZW1uj3XGEPk4M88KF97cURaFhXn9XWmACnSjjsxNPHboUr451H92KTdeN0fHhFd2nU6fi+yxZW8eVK1ey3BoPnbum99O/cxL0zDliHm310K2hR87R4nFiz5wZoIhKl7ttMkM0BfTI0QXCHNFpoF+7di27F/6vw6G88cYbBDk6QZijE7o+yR+vXJFyOMziDfjbo0fy3ysrbAOHzhDm6Myft7bkf1ZWjoIwZX+5c+foeRyO3HQFYiPM0am/7e7K4WAgf0qw7KLfKv7wxhvyh9VVKQ8ODJwR+owwhwn/u7Ehhy+/LH+9fz+JN+TPN2/KcGlJ/kJZBUYQ5jBDe+lartBa+jf7+ybfGP2w0Q+dP66t0RuHKYQ5zNFauvZ6LYX6UV38Zz97XuOnNg6DTvGm5OfimGek40YeJ/RsNdT1OLWyIj9cW5MftDx79Ditievj/2lzU77Z24v62CHk0g4wG8I8A6+KyAV38Z6d4enoXpAP3PZhKVzUf93ZOTo+X1+X/1pdldXV1aMp+b6bKU+i+3Pq/p46xPA/EquH594OMBlrsyRKY+wdEbksIqcbPIUnbkPdWx28DF/X/PcP3T6WlcFgcBTq+l89fPblvH///tE6LnpoiO+N9MCbnl8MObQD1Hbi2iyEeYLeE5F3RWQu4Kk/E5FfuJ5aLG2EpS6opcE+jQb3NNbD/F3XFlJvB6jtxDCnzJKQcyLy4YxfoevSXt2nrnd23dVVU6QrJM4S1Ck749rBhRbbwT0X6nnMz+0HRrMkQr9Gf9ZSkI96xz3OmdxewExoPfyLloJ81CuuHZzr2wucMMI8ARrkvwv8dXqSsy4wuJBtuex6zTHbAYGeDsLcuCrIY5ujh25K1+2AQLePMDfsYkcXcEUv5N+7ERPojgbpBx23g89oB+YR5kbNuyDt2ll3sw3dqNpBrNLKOHNG2iPGI8yN+tDABVx5xU1IQXzvNRw/HtIFNxwSNhHmBl10AWrJB3zNju6cG11kyXu0A7MIc4MsljVOGwyW3HVZJx9njnZgFpOGjLkY4Gv1MzeD7+nI/zvnfneT0s1lN6EI7TsTYCx5W+3gXTe5jAlFthDmxjTp9TxzYTtufY1qHQ/fpQBOu9r5XXOvWn4st4M598H+UY4vfMIIc0PmG9TKn7h1QSb1lobuIr/nhpr5XMhv0iMba37CsrN1Xfb8uZjtgDC3hTA3xDcIZrmARz12/97nQn7F4M1ZK866GZpdidkOzroPLz7Y7eAGqCE+NdJDEXnL46J67BZSQh66aAfMCrWFMDfE5+L46NgNrjruut4c0tdFO2h7sS/UQ5gb4rMOyu2Gp/+x6VcEs+qiHbBujy2EuSF1hyQ+a9Abq7BdWPq6ageEuS2EecKaXsBCmGeBdgAhzAEgD4R5wkJ8zU1pRELs3uOzyI/nq2/tACcjzA2pGx6nA1zIKV3E9yI/Xio71XfVDkKUdxAOYW6Iz8XxZsPTT2XRpIcd7Bj/sRu/nYIu2gFhbgthbohPGeHdBr2yVyNsEB3CEzchJrahmyGZQqB30Q4eej4e2kGYG+Jzcfhu7XYukR2Ebtecoh5aNeXdenB10Q4YAWMLa7MY4ltGqHZRnzX0zjVYYOlexIlGj42s/VEF+pmIY6t9toqL2Q6esC6LOYS5IUMXlj4LWemF/EXLS5+K6ynHrl1b8TRinfiWZx07ZjuALUVZlt85oaIodkRkmfcqvosBVt5ra1MC/b3nu3hReki/Aew2fNpttYND1w7omXfmWlmWG8cfnJ65MQ/cRdhkt6HTAUY3nCSVoXo5eOrq9E0Ws2qrHXxEkJvEDVCDLC5N+4xFuaJ73+A5HdIOzCLMDXrQwQSZad6nNxbdY4PBeZ12YBZhbtQvDI1vvse+n525bmhZgYdsFWcaYW7UsKOJMsc9YUeiTlXtoOsP9kMj7RHjEeaGabnllx2e3qELcr5Wd+txx/Xzw44nbmE2hLlxtzoK9OoCZpafDbQDTEOYJ6C6kGN91dbSyk+5gM3RdvB65HZAkKeDME/ELXdhtb0B88fucVgRz6YH7oO27bVi7hHkySHME/LYXcjXW+idPXO9PoYg2vfUBe1vWmwHb9EOkkOYJ+i6m04dYtjaE1fCOd/jNVdS9RHtACNYmyUDr7pp3xdnXJf64cjEJL5G54N20BuszZKru8cm9Vwc8zyHXLRZox30G2GeIb4mQ2gHvUPNHAAyQJgDQAYIcwDIAGEOABkgzAEgA4Q5AGSAMAeADBDmAJABwhwAMkCYA0AGCHMAyABhDgBpOTjpbMeF+Q5vLgCYtHvSSdEzB4AMEOYAkIFxYb7HmwsAJtUqsxDmAGBQWZa1boCe+I8BAJ0ajnvwE8O8LMsTu/EAgE6NzeZJN0DHfgIAADoxtmoyKczpnQOALV49c26CAoAthDkAZGBsLk8Kc6b0A4AhkwanUDMHgDQ8mnSWY8PcDUzf500GABMmdrCnrc1C7xwAbGgU5tTNAcCGiXlMmAOAfcNpM/Mnhrn7YWaCAkC3pnasZ1nPnN45AHSLMAeADGxPewpFWZaT/0FRLInIV7QGAOjEflmWS9MeeGrPvCzLvWmD1QEArZnaK58pzB1KLQDQjZnCfGqZRZ6XWgYi8iVvJABEpUMSF2Z5wJl65m6IIlP7ASCumXrlUqPMorZ4EwEgqs1ZH2ymMoswqgUAYptpFEtl5p65G9Vyn7cTAKKoVQ2pU2YRSi0AEE2tvJ25zPL3HygKXed8nvcTAFpzpyzL1Tq/vG7PXOidA0DrZr7xWfHpmXMjFADaU+vGZ6V2z9zdCL3JGwkArdjw+aW1e+bCjFAAaItXr1w8a+bVjFCGKQJAWN73JL165vK8d74iIp/zRgJAELqr21JZlgc+v8yrZy7Pe+c79M4BIJhN3yCXJj1zoXYOAKF418or3j1zeVE7Z2QLADTjNYJlVKOeubwYd77LrFAA8PKoLMtB05euUc9cXow7rz1bCQBwZD3Ey9C4Zy7Pe+cLrne+GOKkAKAnbpZluRbiqQYJc2GoIgDU1Wgo4nGNyywVN1TxDm8nAMxkI1SQS8ieubwot+xxMxQAJrpfluVKyJcoWM9cnvfO9VMmSP0HADI1bCMng4a5PA/0bcotADDWhhsFGFTQMkuF0S0AcKLaOwjNqpUwF0a3AMBx+yIyCHnTc1TwMkvFjW651tbvB4DErLYV5NJmmMvzQN+gfg4A8mu3llVrWiuzVFz9XHvp53k/AfRQsFmek7Qe5vJiqdwdxp8D6JlHIrLSZnmlEiXMhRuiAPon6HT9aVqtmY9yN0SvxHo8AOjQMFaPvBItzOV5oG8xwgVAD6y2fcPzuKhhLi9GuLA7EYBcXXGViKiih7k8D/Q1Ah1Ahq64CkR0nYS5EOgA8tNZkEuXYS4EOoB8dBrk0nWYC4EOIH2dB7lYCHMh0AGkaWglyCXmpKFZFEWhoX7DzAkBwMmqceRRhx9OYqJnXnGfcFfcCwUAFj2yFuRirWdeYS0XAEbdb3spW1+meuYV94m35D4BAcACXf0w6hT9OkyGubjNocuy1B76bw2cDoD+qm50mt6s3mSZ5biiKHTPvC3KLgAi0+rAmrX6+EnM9sxHuR3/B65eBQAx/Nbijc5xkuiZjyqKQhfqumrnjABkZuhuckZfLKuJJHrmo9yqiy9zcxRAC266DSWSCnJJMczFjXZxN0d/zZh0AAHsi8jP9Can1dEq0yQZ5pWyLDddLZ2lAAD40M7gtbIsk+yNj0quZj6O22NUSzDLNs8QgDHaCdwoy3IvhzcmmzCvuPVdNNQXbZwRAGPuuxBPuid+XHZhXiHUARyTZYhXsg3zCqEO9F7WIV7JPswrbhbpOjV1oDe0Jr6ZyqSfpnoT5pWiKJZcT32V5QGA7Oy7pT82Ux1i6Kt3YV4pimLBBboel2ycFQAPOrxQl/zYyr2UMklvw3yU661rqGt9/bydMwMwwR0X4tt964WfhDA/5liPfYVSDGDGvtu0ZtstvocRhPkUbjJSdQwIdyAaDe/dkQDPYnJPWwjzmtyWdscPAh5oRoN7zwW3Bvgu4V0PYR6AK80M3FZ3elR/Fvdnxrij73SV06quXd2k1NA+6PNNy5AIcwDIQNKrJgIAniPMASADhDkAZIAwB4DUicj/A2sRCWLPVF1BAAAAAElFTkSuQmCC
      mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - RHOAM
    - Integration
  labels:
    alm-owner-rhoam: rhoam-operator
    operated-by: rhoam-operator
  maintainers:
    - email: rhoam-support@redhat.com
      name: rhoam
  links: []
  maturity: alpha
  provider:
    name: rhoam
  selector:
    matchLabels:
      alm-owner-rhoam: rhoam-operator
      operated-by: rhoam-operator
  version: 1.43.0
  replaces: managed-api-service.v1.42.0
